# This file was generated by GoReleaser. DO NOT EDIT.
cask "chartbrew" do
  version "0.0.2"

  on_macos do
    on_intel do
      sha256 "fdd76a69e9a04b82ad22ca6b470398255ceffda9fab6747ce61004b285ce2697"
      url "https://github.com/ba0f3/chartbrew-cli/releases/download/v#{version}/chartbrew_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "bb11a5c4c03641a2c7f914174337d8d89deb8332a098fbe9ae64062e8b73d5b2"
      url "https://github.com/ba0f3/chartbrew-cli/releases/download/v#{version}/chartbrew_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f6336be9b74b325098ef2db5904446871cedb97623a8274172afb1ee6e94e7c3"
      url "https://github.com/ba0f3/chartbrew-cli/releases/download/v#{version}/chartbrew_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "e183b53ac8403e8a7b373ed02571920cf5f57ec239becfb9d458894438ab3f30"
      url "https://github.com/ba0f3/chartbrew-cli/releases/download/v#{version}/chartbrew_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "chartbrew"
  desc "Agent-first CLI for the Chartbrew API"
  homepage "https://github.com/ba0f3/chartbrew-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chartbrew"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/chartbrew"]
    end
  end

  # No zap stanza required

end
