# This file was generated by GoReleaser. DO NOT EDIT.
cask "chartbrew" do
  version "0.0.1"

  on_macos do
    on_intel do
      sha256 "468aeb00f4f21a5bb49979bf505113c247b88264df1b3b4a495d28f807b8f853"
      url "https://github.com/ba0f3/chartbrew-cli/releases/download/v#{version}/chartbrew_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "573326b3e68384a43544d9d1dc80b13dca5615787b9f6495d17ecc0415839746"
      url "https://github.com/ba0f3/chartbrew-cli/releases/download/v#{version}/chartbrew_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "62d65ce5d72aae36d87845f130cecc301000a113fd61a7c56d7571e936e42e1e"
      url "https://github.com/ba0f3/chartbrew-cli/releases/download/v#{version}/chartbrew_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "46930362e03d7f1f1d295f313c4cf7071f73527f59137bf9be9b0909495e1d06"
      url "https://github.com/ba0f3/chartbrew-cli/releases/download/v#{version}/chartbrew_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "chartbrew"
  desc "Agent-first CLI for the Chartbrew API"
  homepage "https://github.com/ba0f3/chartbrew-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chartbrew"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/chartbrew"]
    end
  end

  # No zap stanza required

end
