# This file was generated by GoReleaser. DO NOT EDIT.
cask "chartbrew" do
  version "0.0.3"

  on_macos do
    on_intel do
      sha256 "3774e31430143b695e2c09536c5f293a2858e6dee687ecbf1f055a1418671a46"
      url "https://github.com/ba0f3/chartbrew-cli/releases/download/v#{version}/chartbrew_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "8aa715ca40458fbf29689ebe0d6961a6d8d0a9816df8e1cbffa357f146628d7e"
      url "https://github.com/ba0f3/chartbrew-cli/releases/download/v#{version}/chartbrew_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "cb9e92c9340cbb5676cbd9e1e889bdd59552978b226d72791cc34137b2c119fa"
      url "https://github.com/ba0f3/chartbrew-cli/releases/download/v#{version}/chartbrew_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "3e6452b27a8945d6a45869aa5ea4060ef9868a9c0ede1d5b83a57934aa7bd4f8"
      url "https://github.com/ba0f3/chartbrew-cli/releases/download/v#{version}/chartbrew_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "chartbrew"
  desc "Agent-first CLI for the Chartbrew API"
  homepage "https://github.com/ba0f3/chartbrew-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chartbrew"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/chartbrew"] if OS.mac?
  end

  # No zap stanza required

end
