# This file was generated by GoReleaser. DO NOT EDIT.
cask "op" do
  version "0.1.5"

  on_macos do
    on_intel do
      sha256 "7e70b845ca201e0c3b84a441b826cd13a97852808a0c8cb77143007b06e386e5"
      url "https://github.com/ba0f3/openproject-cli/releases/download/v#{version}/openproject-cli_darwin_amd64_v#{version}.zip"
    end
    on_arm do
      sha256 "c32d8a4efca4202b01d0b8fa79cb9a3e3384cdd0d4acc9f683f96d9e149aa883"
      url "https://github.com/ba0f3/openproject-cli/releases/download/v#{version}/openproject-cli_darwin_arm64_v#{version}.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "1aa55be8489770010b1cc49911c58f084245563da53be65bd4dc2700380abeb8"
      url "https://github.com/ba0f3/openproject-cli/releases/download/v#{version}/openproject-cli_linux_amd64_v#{version}.zip"
    end
    on_arm do
      sha256 "d4f3fabf907c56179d23481e210b8dc1ef9ad9b3257559ca2abf5a3486420e63"
      url "https://github.com/ba0f3/openproject-cli/releases/download/v#{version}/openproject-cli_linux_arm64_v#{version}.zip"
    end
  end

  name "op"
  desc "An easy to use CLI for the OpenProject APIv3"
  homepage "https://github.com/ba0f3/openproject-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "op"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/op"] if OS.mac?
  end

  # No zap stanza required

end
