# This file was generated by GoReleaser. DO NOT EDIT.
cask "op" do
  version "0.1.4"

  on_macos do
    on_intel do
      sha256 "3656929665c93199af430b49ac01418dd05781f540f3aaad6fc7f0e78b113140"
      url "https://github.com/ba0f3/openproject-cli/releases/download/v#{version}/openproject-cli_darwin_amd64_v#{version}.zip"
    end
    on_arm do
      sha256 "65d086168f6d57b6f6770880fcc9908430ae2c8078678f2667bd406d8454c45d"
      url "https://github.com/ba0f3/openproject-cli/releases/download/v#{version}/openproject-cli_darwin_arm64_v#{version}.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "7729fc21b74a1f3ebbb42935eb067b604f8ca15849f67efdd6650ce0edecaa67"
      url "https://github.com/ba0f3/openproject-cli/releases/download/v#{version}/openproject-cli_linux_amd64_v#{version}.zip"
    end
    on_arm do
      sha256 "87916e61a9a6b642920b3d3ed1a898ffe4846469f4d43d70566e269c003cff53"
      url "https://github.com/ba0f3/openproject-cli/releases/download/v#{version}/openproject-cli_linux_arm64_v#{version}.zip"
    end
  end

  name "op"
  desc "An easy to use CLI for the OpenProject APIv3"
  homepage "https://github.com/ba0f3/openproject-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "op"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/chartbrew"]
    end
  end

  # No zap stanza required

end
