# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Op < Formula
  desc "An easy to use CLI for the OpenProject APIv3"
  homepage "https://github.com/ba0f3/openproject-cli"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ba0f3/openproject-cli/releases/download/v0.1.1/openproject-cli_darwin_amd64_v0.1.1.zip"
      sha256 "5a22827b38d532b1f8817765dd0c00246a0bc54ad3f54e7855d1eb84a086d832"

      define_method(:install) do
        bin.install "op"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ba0f3/openproject-cli/releases/download/v0.1.1/openproject-cli_darwin_arm64_v0.1.1.zip"
      sha256 "d1f029880fbb15b6a62352ec1ea831ef4d0a8cbc693ab0e89f7508d42c3f1c69"

      define_method(:install) do
        bin.install "op"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ba0f3/openproject-cli/releases/download/v0.1.1/openproject-cli_linux_amd64_v0.1.1.zip"
      sha256 "a6c9d9f98ca07c86d58e01b9279ef3b057a345440e4f425dd8094ad201c978ab"
      define_method(:install) do
        bin.install "op"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ba0f3/openproject-cli/releases/download/v0.1.1/openproject-cli_linux_arm64_v0.1.1.zip"
      sha256 "4af21e48bd5d79b7bcea40bec0a26144583c09dbf7ccfafb239d06a6a575f3aa"
      define_method(:install) do
        bin.install "op"
      end
    end
  end

  test do
    system "#{bin}/op", "--version"
  end
end
