# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WazuhCli < Formula
  desc "AI-agent-first CLI for the Wazuh Server API"
  homepage "https://github.com/ba0f3/wazuh-cli"
  version "0.1.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ba0f3/wazuh-cli/releases/download/v0.1.9/wazuh-cli_Darwin_x86_64.tar.gz"
      sha256 "f21eb5df1b17464b4c71a5a2445ef1779ae6196ad60dc4451de8c78d189f3a27"

      define_method(:install) do
        bin.install "wazuh-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ba0f3/wazuh-cli/releases/download/v0.1.9/wazuh-cli_Darwin_arm64.tar.gz"
      sha256 "dc53a7f15eba3704d1c7bfef38df603e584f93924ca860246778f42810929be9"

      define_method(:install) do
        bin.install "wazuh-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ba0f3/wazuh-cli/releases/download/v0.1.9/wazuh-cli_Linux_x86_64.tar.gz"
      sha256 "f4dd5aada7ae115fca95a352c65ff6811d303189be38396854b7aac893a2d3c6"
      define_method(:install) do
        bin.install "wazuh-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ba0f3/wazuh-cli/releases/download/v0.1.9/wazuh-cli_Linux_arm64.tar.gz"
      sha256 "3d0aa95dd1bd50604275d2632a32deee223c6827ed8c171e84d7887d951fdf47"
      define_method(:install) do
        bin.install "wazuh-cli"
      end
    end
  end

  test do
    system "#{bin}/wazuh-cli", "--version"
  end
end
