# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WazuhCli < Formula
  desc "The AI-agent-first CLI for the Wazuh Server API"
  homepage "https://github.com/ba0f3/wazuh-cli"
  version "0.1.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ba0f3/wazuh-cli/releases/download/v0.1.7/wazuh-cli_Darwin_x86_64.tar.gz"
      sha256 "90bb2cf78c1cce53dd1675a37b5e3176974f29835ce747b555060c1eb765f56c"

      define_method(:install) do
        bin.install "wazuh-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ba0f3/wazuh-cli/releases/download/v0.1.7/wazuh-cli_Darwin_arm64.tar.gz"
      sha256 "92a982d512843c71921bd1a9b6cebedc841015f753bcafb7ae51e148d04c5be4"

      define_method(:install) do
        bin.install "wazuh-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ba0f3/wazuh-cli/releases/download/v0.1.7/wazuh-cli_Linux_x86_64.tar.gz"
      sha256 "e1693067842bb40581b595dc8e7a98537a4bc4d07d31b806567badca62520116"
      define_method(:install) do
        bin.install "wazuh-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ba0f3/wazuh-cli/releases/download/v0.1.7/wazuh-cli_Linux_arm64.tar.gz"
      sha256 "ba290e3740231d77cf90c0de2d174f7d0cba9a26bde8d56c9245c338591b3af8"
      define_method(:install) do
        bin.install "wazuh-cli"
      end
    end
  end

  test do
    system "#{bin}/wazuh-cli --version"
  end
end
