# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WazuhCli < Formula
  desc "AI-agent-first CLI for the Wazuh Server API"
  homepage "https://github.com/ba0f3/wazuh-cli"
  version "0.1.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ba0f3/wazuh-cli/releases/download/v0.1.8/wazuh-cli_Darwin_x86_64.tar.gz"
      sha256 "36668ff4bd39c562a5675fe09dad86989a2e319d53c2546848c954f755ec0869"

      define_method(:install) do
        bin.install "wazuh-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ba0f3/wazuh-cli/releases/download/v0.1.8/wazuh-cli_Darwin_arm64.tar.gz"
      sha256 "90d9986579dcba1ff3c33c6f0d23b8ff5d512780ce90d32825ef19f44f9c02f3"

      define_method(:install) do
        bin.install "wazuh-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ba0f3/wazuh-cli/releases/download/v0.1.8/wazuh-cli_Linux_x86_64.tar.gz"
      sha256 "9f7820deec82c0138eec47382d151d2f7c41c07664a5ffa23adf0257a771f237"
      define_method(:install) do
        bin.install "wazuh-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ba0f3/wazuh-cli/releases/download/v0.1.8/wazuh-cli_Linux_arm64.tar.gz"
      sha256 "5ca135edbb9c8250fe67149175f40e7103ec0f81689e8db6b5951e804d35373d"
      define_method(:install) do
        bin.install "wazuh-cli"
      end
    end
  end

  test do
    system "#{bin}/wazuh-cli", "--version"
  end
end
